---
#- become: true
- name: copy pom.xml to tmp
  copy:
    src: pom.xml
    dest: /tmp

- name: Copying svcstart.sh script to server
  copy:
    src: svcstart.sh 
    dest: /svcstart.sh
    mode: 0777

- name: Execute the Script
  command: sh /svcstart.sh

  #- name: create appsvr directory
  #file:
  #    path: /appserver
  #    state: directory
  #    mode: 0777

  
